// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbO0inhVA2KLYaBUtaxAKU2kprjw7SgD4',
    appId: '1:835235978526:web:dc2bc284a7fb1234e57d0f',
    messagingSenderId: '835235978526',
    projectId: 'homiex-74479',
    authDomain: 'homiex-74479.firebaseapp.com',
    storageBucket: 'homiex-74479.firebasestorage.app',
    measurementId: 'G-R4LCLW0FPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmQawvv7qIsVZZvdhYbH5FGECjHfkIe74',
    appId: '1:835235978526:android:0b1ab7be4fe2323ce57d0f',
    messagingSenderId: '835235978526',
    projectId: 'homiex-74479',
    storageBucket: 'homiex-74479.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzMjb_xj4QnasZnCVKjDLHyiydRjN6lgo',
    appId: '1:835235978526:ios:d41eb10a124ac22de57d0f',
    messagingSenderId: '835235978526',
    projectId: 'homiex-74479',
    storageBucket: 'homiex-74479.firebasestorage.app',
    iosClientId: '835235978526-fmn8ijf54pgpo92en903b0g2nivs8h94.apps.googleusercontent.com',
    iosBundleId: 'com.example.homix',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzMjb_xj4QnasZnCVKjDLHyiydRjN6lgo',
    appId: '1:835235978526:ios:d41eb10a124ac22de57d0f',
    messagingSenderId: '835235978526',
    projectId: 'homiex-74479',
    storageBucket: 'homiex-74479.firebasestorage.app',
    iosClientId: '835235978526-fmn8ijf54pgpo92en903b0g2nivs8h94.apps.googleusercontent.com',
    iosBundleId: 'com.example.homix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbO0inhVA2KLYaBUtaxAKU2kprjw7SgD4',
    appId: '1:835235978526:web:6228f7bbfd75b92ce57d0f',
    messagingSenderId: '835235978526',
    projectId: 'homiex-74479',
    authDomain: 'homiex-74479.firebaseapp.com',
    storageBucket: 'homiex-74479.firebasestorage.app',
    measurementId: 'G-HV9HE5XT9C',
  );
}
